// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ModelLib
{
    public partial class Subjects
    {
        public Subjects()
        {
            
        }

        public int Id { get; set; }
        public string SubjectName { get; set; }
        public DateTime? SubjectMeetTime { get; set; }

        public Subjects(string subjectName, DateTime? subjectMeetTime)
        {
            SubjectName = subjectName;
            SubjectMeetTime = subjectMeetTime;
        }

        public override bool Equals(object obj)
        {
            return obj is Subjects subjects &&
                   Id == subjects.Id &&
                   SubjectName == subjects.SubjectName &&
                   SubjectMeetTime == subjects.SubjectMeetTime;
        }
    }
}