// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ModelLib
{
    public partial record Subjects
    {
        private HashSet<PiData> PiData;
        public Subjects()
        {

            PiData = new HashSet<PiData>();
        }

        public Subjects( string subjectName, DateTime? subjectMeetTime)
        {
            Id = idCounter++;
            SubjectName = subjectName;
            SubjectMeetTime = subjectMeetTime;
        }

        public Subjects(int id, string subjectName, DateTime? subjectMeetTime)
        {
            Id = id;
            SubjectName = subjectName;
            SubjectMeetTime = subjectMeetTime;

        }

        private static int idCounter = 0;
        private int _id;
        private string _subjectName;

        public int Id 
        {
            get => _id;
            set
            {
                if (value < 0) throw new ArgumentOutOfRangeException();
                _id = value;
            }
        }
        public string SubjectName 
        {
            get => _subjectName;
            set
            {
                if (value == null) { throw new ArgumentNullException(); }
                if (value.Length < 1) { throw new ArgumentException(); }
                _subjectName = value;
            }
        }

        public DateTime? SubjectMeetTime { get; set; }

        public virtual bool Equals(Subjects obj)
        {
            // Checking Date Property goes wrong because computers are poor at dealing with long integers, so we test for year, day, month speceficily 
            return obj is Subjects subjects &&
                   Id == subjects.Id &&
                   SubjectName == subjects.SubjectName &&
                   SubjectMeetTime.Value.Day == subjects.SubjectMeetTime.Value.Day &&
                   SubjectMeetTime.Value.Year == subjects.SubjectMeetTime.Value.Year
                   &&
                   SubjectMeetTime.Value.Month == subjects.SubjectMeetTime.Value.Month;
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override string ToString()
        {
            return $"Id: {Id}, SubjectName: {SubjectName}, SubjectMeetTime:{SubjectMeetTime}";

        }
    }
}