// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ModelLib
{
    public partial record Subjects
    {
        public Subjects()
        {
            PiData = new HashSet<PiData>();
        }

        public Subjects( string subjectName, DateTime? subjectMeetTime)
        {
            Id = idCounter++;
            SubjectName = subjectName;
            SubjectMeetTime = subjectMeetTime;
        }

        public Subjects(int id, string subjectName, DateTime? subjectMeetTime)
        {
            Id = id;
            SubjectName = subjectName;
            SubjectMeetTime = subjectMeetTime;
        }

        private static int idCounter = 0;
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public DateTime? SubjectMeetTime { get; set; }

        public virtual ICollection<PiData> PiData { get; set; }

        public virtual bool Equals(Subjects obj)
        {
            // Checking Date Property goes wrong because computers are poor at dealing with long integers, so we test for year, day, month speceficily 
            return obj is Subjects subjects &&
                   Id == subjects.Id &&
                   SubjectName == subjects.SubjectName &&
                   SubjectMeetTime.Value.Day == subjects.SubjectMeetTime.Value.Day &&
                   SubjectMeetTime.Value.Year == subjects.SubjectMeetTime.Value.Year
                   &&
                   SubjectMeetTime.Value.Month == subjects.SubjectMeetTime.Value.Month;
        }
        public override string ToString()
        {
            return $"Id: {Id}, SubjectName: {SubjectName}, SubjectMeetTime:{SubjectMeetTime}";
        }
    }
}